# -*- coding: utf-8 -*-
"""SocialMedia_Ads_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2BLLoIbEEu2Hx7byOVb7_w2zPIYqyxG
"""

import numpy as np
import pandas as pd
import seaborn as sbs
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/social.csv")
print(data.head())

data.describe()

data.info()

data.isna().sum()

plt.figure(figsize=(10, 10))
plt.title("Product Purchased By People Through Social Media Marketing")
sbs.histplot(x="Age", hue="Purchased", data=data)
plt.show()

plt.figure(figsize= (10,10))
plt.title("Product Purchased By People According to Their Income")
sbs.histplot(x="EstimatedSalary", hue="Purchased", data=data)
plt.show()

X = data.drop('Purchased', axis = 1)
y = data['Purchased']

np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print(classification_report(y_test, pred))

